name: Publish GitHub Pages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build_and_deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Inspect files before checkout
        run: ls -la
      - name: show current directory before checkout
        run: pwd
      - uses: actions/checkout@v3
      - name: Inspect files after checkout
        run: ls -la
      - name: show current directory after checkout
        run: pwd
      - name: Add Mask
        run: |
          echo "::add-mask::${{ secrets.ALBUM_URL_1 }}"
          echo "::add-mask::${{ secrets.ALBUM_URL_2 }}"
          echo "::add-mask::${{ secrets.ALBUM_URL_3 }}"
          echo "::add-mask::${{ secrets.ALBUM_URL_4 }}"
          echo "::add-mask::${{ secrets.ALBUM_URL_5 }}"
          echo "::add-mask::${{ secrets.ALBUM_URL_6 }}"
          echo "::add-mask::${{ secrets.ALBUM_URL_7 }}"
          echo "::add-mask::${{ secrets.ALBUM_URL_8 }}"
          echo "::add-mask::${{ secrets.ALBUM_URL_9 }}"
          echo "::add-mask::${{ secrets.ALBUM_URL_10 }}"
          echo "::add-mask::${{ secrets.BLUE_ALBUM_URL_1 }}"
          echo "::add-mask::${{ secrets.BLUE_ALBUM_URL_2 }}"
          echo "::add-mask::${{ secrets.BLUE_ALBUM_URL_3 }}"
          echo "::add-mask::${{ secrets.KEISOTSU_EXTERNALDATA_URL }}"
      - name: copyfiles
        run: |
          curl -o export/photo/album/1.jpg ${{ secrets.ALBUM_URL_1 }}
          curl -o export/photo/album/2.jpg ${{ secrets.ALBUM_URL_2 }}
          curl -o export/photo/album/3.jpg ${{ secrets.ALBUM_URL_3 }}
          curl -o export/photo/album/4.jpg ${{ secrets.ALBUM_URL_4 }}
          curl -o export/photo/album/5.jpg ${{ secrets.ALBUM_URL_5 }}
          curl -o export/photo/album/6.jpg ${{ secrets.ALBUM_URL_6 }}
          curl -o export/photo/album/7.jpg ${{ secrets.ALBUM_URL_7 }}
          curl -o export/photo/album/8.jpg ${{ secrets.ALBUM_URL_8 }}
          curl -o export/photo/album/9.jpg ${{ secrets.ALBUM_URL_9 }}
          curl -o export/photo/album/10.jpg ${{ secrets.ALBUM_URL_10 }}
          curl -o export/photo/blue/1.jpg ${{ secrets.BLUE_ALBUM_URL_1 }}
          curl -o export/photo/blue/2.jpg ${{ secrets.BLUE_ALBUM_URL_2 }}
          curl -o export/photo/blue/3.jpg ${{ secrets.BLUE_ALBUM_URL_3 }}
          curl -o export/external_data.json ${{ secrets.KEISOTSU_EXTERNALDATA_URL }}
      - uses: actions/upload-artifact@v4
        with:
          name: my_site
          path: export
      - uses: actions/upload-pages-artifact@v3
        with:
          path: export

  deploy:
    needs: build
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
